### ISSUE TITLE
Montage previews cannot be closed on macOS

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#253] opened 2022-02-02 21:04 UTC
When previewing a montage (_Edit_ – _Set montage..._, select any montage and click on _View_), the montage previews that open in a separate window cannot be closed as long as the _Set montage_ dialog is still open.

**Comment by hofaflo** [comment] 2022-02-05 23:29
Cannot reproduce on Win10, multiple montage preview windows can be closed independent of the "Set montag" dialog's state 🤔

**Comment by cbrnr** [comment] 2023-12-28 09:00
A nice solution would be to include the previews in the montage dialog, perhaps with a collapsible "Details" button.

**Closed** 2024-12-09 07:10 UTC
Labels: bug, macos
