### ISSUE TITLE
wrong units when reading xdf

### ISSUE THREAD

**Issue by pmavros** [cbrnr/mnelab#383] opened 2023-06-28 09:21 UTC
Hello, 

thanks for the xdf parser, it is indeed very practical.

I am using `read_raw_xdf` to read an eeg recording, but the data come without the appropriate type (i.e. "Good channels | 24 misc". 

I then use `raw.set_channel_types(dict(zip(raw.ch_names, ['eeg']*len(raw.ch_names))))` to fix this, which seems to work because the channel type gets renamed in the info. 

However when i then try to plot the data `raw.plot()` the signal is completely out of place, which is suspect has to do somethign with the units? how could i correct this? 

Thanks!

**Comment by cbrnr** [comment] 2023-06-28 11:48
MNELAB uses the `type` field in each stream header to assign the most suitable channel type. Currently, this should work for EEG data – I'd be curious to see what the `type` field(s) in your header say. You can check this if you open the XDF file with MNELAB (the GUI) and then select "File" – "Show XDF metadata".

If you change the channel type, signals are never rescaled, so I suspect that's what you're seeing. Usually, the problem is that the data is in µV, whereas MNE expects EEG data in V. Therefore, you need to multiply all channels by `1e-6`. You can do this with [`raw.apply_function()`](https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.apply_function) like so:

```python
raw.apply_function(lambda x: x * 1e-6)
```

**Comment by pmavros** [comment] 2023-06-28 12:32
Hi Clemens, 

Thanks – that's what i figured. I tried your suggestion but the scaling isnot working just yet. The type field appears as "misc". For the record, this is EEG data collected with MBrainTrain Smarting Mobi. The EEG values are initially `raw[1,1]` -10793.90332031 and after applying your code -0.0108684. I am trying to figure out what is mne's expectation.

**Comment by cbrnr** [comment] 2023-06-28 13:56
> The type field appears as "misc".

So this means that the function assigns the correct channel type, no?

> OK rereading your message, I just realised the issue; my data needed rescaleing by 1e-7. That works fine.

That's a weird scaling factor. The original scaling is in units of 10µV?

**Comment by cbrnr** [comment] 2023-12-26 13:41
Closing since the issue has probably been resolved.

**Closed by cbrnr** 2023-12-26 13:41 UTC
